### ISSUE TITLE
请问下，MP4格式咋加载哈？

### ISSUE THREAD

**Issue by Chen7969663** [SABERBOY/CocosCreator3DPlayable#8]
最近搞广告还需要加一小段视频，你的这个方案不支持MP4视频哈。这个怎么修改你知道吗?
期待你的回复。

**Comment by SABERBOY** [comment]
**该项目只提供解决方案,暂不提供自定义方案,需要自行查看代码然后修改的,当然可以提供技术支持的 :shipit:**

**Comment by SABERBOY** [comment]
具体修改查看该文件的[地址](https://github.com/SABERBOY/CocosCreator3DPlayable/blob/main/fileEmbed/plugin/new-res-loader.js)注册对应MP4文件的加载流程
